# Generated by Django 6.0.4 on 2026-06-11 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_alter_companies_nip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("ALL", "Cały Ślad Węglowy"),
                            ("Z1", "Zakres 1"),
                            ("Z2", "Zakres 2"),
                        ],
                        default="ALL",
                        max_length=10,
                        verbose_name="Zakres merytoryczny",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Sesja aktywna"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to="companies.companies",
                        verbose_name="Analizowana Spółka",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesja Czatu AI",
                "verbose_name_plural": "Sesje Czatu AI",
                "db_table": "tbl_ai_chat_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Użytkownik"),
                            ("assistant", "Asystent AI"),
                            ("system", "System / Kontekst"),
                        ],
                        max_length=20,
                        verbose_name="Rola",
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść wiadomości")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_services.aichatsession",
                        verbose_name="Sesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiadomość AI",
                "verbose_name_plural": "Wiadomości AI",
                "db_table": "tbl_ai_chat_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
