# Generated by Django 6.0.4 on 2026-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companies",
            name="nip",
            field=models.CharField(max_length=10, unique=True, verbose_name="Nip code"),
        ),
    ]
