# Generated by Django 6.0.4 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_companies_nip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companies",
            options={"verbose_name": "Spółka", "verbose_name_plural": "Spółki"},
        ),
        migrations.AddField(
            model_name="companies",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Jeśli odznaczone, spółka nie będzie uwzględniana w procesach raportowania.",
                verbose_name="Czy spółka aktywna",
            ),
        ),
    ]
