# Generated by Django 6.0.4 on 2026-08-09 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_options_companies_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companiesgroup',
            options={'verbose_name': 'Grupa kapitałowa', 'verbose_name_plural': 'Grupy kapitałowe'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='capital_group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', related_query_name='company', to='companies.companiesgroup', verbose_name='Grupa kapitałowa'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='countries', related_query_name='country', to='companies.countries', verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='krs',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numer KRS'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa firmy'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='nip',
            field=models.CharField(max_length=10, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='regon',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numer REGON'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='zip',
            field=models.CharField(max_length=20, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='gk_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa grupy kapitałowej'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='lvl_in_structure',
            field=models.IntegerField(verbose_name='Poziom w strukturze'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='companiesgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='code_alfa_2',
            field=models.CharField(max_length=2, unique=True, verbose_name='Kod Alfa-2'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Nazwa kraju'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
    ]
