# Generated by Django 6.0.4 on 2026-08-09 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companiesgroup_options_alter_countries_options_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyreportenvelope',
            options={'verbose_name': 'Koperta raportowa spółki', 'verbose_name_plural': 'Koperty raportowe spółek'},
        ),
        migrations.AlterModelOptions(
            name='recordcomment',
            options={'verbose_name': 'Komentarz do rekordu', 'verbose_name_plural': 'Komentarze do rekordów'},
        ),
        migrations.AlterModelOptions(
            name='reportingperiod',
            options={'verbose_name': 'Okres raportowy', 'verbose_name_plural': 'Okresy raportowe'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania'},
        ),
        migrations.AlterField(
            model_name='companyreportenvelope',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='companyreportenvelope',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.reportingperiod', verbose_name='Okres'),
        ),
        migrations.AlterField(
            model_name='companyreportenvelope',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otwarte do wprowadzania'), ('IN_REVIEW', 'W weryfikacji przez Admina (zablokowane dla usera)'), ('RETURNED', 'Zwrócone do poprawy (odblokowane)'), ('APPROVED', 'Zatwierdzone (całkowita blokada)')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Rozwiązany'),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='text',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='deadline',
            field=models.DateField(verbose_name='Ostateczny termin'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Rok raportowy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Przypisany do'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Ukończone'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DATA_ENTRY', 'Wprowadzenie danych'), ('CORRECTION', 'Poprawa odrzuconych rekordów'), ('UNLOCK_REQ', 'Wniosek o odblokowanie'), ('CUSTOM', 'Zadanie Ad-Hoc')], max_length=20, verbose_name='Typ zadania'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
    ]
