# Generated by Django 6.0.4 on 2026-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_companyreportenvelope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='action_type',
            field=models.CharField(blank=True, choices=[('status_pending', 'Status zmieniony na oczekujący'), ('data_collection', 'Zbieranie danych'), ('clarification', 'Wymagane wyjaśnienie'), ('report_returned', 'Raport zwrócony')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
