# Generated by Django 6.0.4 on 2026-05-17 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id_rejestr_zmian",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=100)),
                ("date_change", models.DateTimeField()),
                ("table_name", models.CharField(max_length=200)),
                ("record_id", models.CharField(max_length=50)),
                ("change_type", models.CharField(max_length=10)),
                ("previous_data", models.TextField(blank=True, null=True)),
                ("actual_data", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log zmian",
                "verbose_name_plural": "Logi zmian",
                "db_table": "tbl_change_log",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("sender", models.CharField(max_length=100)),
                ("recipients", models.CharField(max_length=1000)),
                ("company", models.CharField(max_length=200)),
                ("table_name", models.CharField(blank=True, max_length=200, null=True)),
                ("record_ids", models.CharField(blank=True, max_length=500, null=True)),
                ("template_type", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=500)),
                ("scope", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log email",
                "verbose_name_plural": "Logi email",
                "db_table": "tbl_email_log",
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor_name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("factor", models.DecimalField(decimal_places=5, max_digits=12)),
                ("unit_factor", models.CharField(max_length=50)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Wskaźnik emisji",
                "verbose_name_plural": "Wskaźniki emisji",
                "db_table": "tbl_factors",
            },
        ),
        migrations.CreateModel(
            name="EnergyConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("energy_source", models.CharField(max_length=100)),
                ("energy_type", models.CharField(max_length=100)),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Zużycie energii",
                "verbose_name_plural": "Zużycie energii",
                "db_table": "tbl_e_cons",
            },
        ),
        migrations.CreateModel(
            name="EnergyProduced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "installation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("energy_type", models.CharField(max_length=100)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
            ],
            options={
                "verbose_name": "Wyprodukowana energia",
                "verbose_name_plural": "Wyprodukowana energia",
                "db_table": "tbl_e_prod",
            },
        ),
        migrations.CreateModel(
            name="EnergyPurchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("energy_type", models.CharField(max_length=100)),
                ("trader", models.CharField(blank=True, default="", max_length=200)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Zakupiona energia",
                "verbose_name_plural": "Zakupiona energia",
                "db_table": "tbl_e_purc",
            },
        ),
        migrations.CreateModel(
            name="EnergySold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("energy_type", models.CharField(max_length=100)),
                ("customer", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Sprzedana energia",
                "verbose_name_plural": "Sprzedana energia",
                "db_table": "tbl_e_sold",
            },
        ),
        migrations.CreateModel(
            name="FugitiveEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("installation", models.CharField(max_length=200)),
                ("product", models.CharField(max_length=200)),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("raport", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Emisja niezorganizowana",
                "verbose_name_plural": "Emisje niezorganizowane",
                "db_table": "tbl_fugitive_emissions",
            },
        ),
        migrations.CreateModel(
            name="MobileCombustion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("vehicle", models.CharField(max_length=200)),
                ("fuel", models.CharField(max_length=100)),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("raport", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Spalanie mobilne",
                "verbose_name_plural": "Spalanie mobilne",
                "db_table": "tbl_mobile_combustion",
            },
        ),
        migrations.CreateModel(
            name="ProcessEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("process", models.CharField(max_length=200)),
                ("product", models.CharField(max_length=200)),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("raport", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Emisja procesowa",
                "verbose_name_plural": "Emisje procesowe",
                "db_table": "tbl_process_emissions",
            },
        ),
        migrations.CreateModel(
            name="ReductionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("target_name", models.CharField(max_length=300)),
                ("base_year", models.PositiveIntegerField()),
                ("target_year", models.PositiveIntegerField()),
                ("reduction_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scope", models.CharField(default="1+2", max_length=10)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Cel redukcji",
                "verbose_name_plural": "Cele redukcji",
                "db_table": "tbl_reduction_targets",
            },
        ),
        migrations.CreateModel(
            name="StationaryCombustion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("company", models.CharField(max_length=200)),
                (
                    "data_quality",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("fuel", models.CharField(max_length=100)),
                ("installation", models.CharField(max_length=200)),
                (
                    "emission_tco2eq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("raport", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Spalanie stacjonarne",
                "verbose_name_plural": "Spalanie stacjonarne",
                "db_table": "tbl_stationary_combustion",
            },
        ),
        migrations.CreateModel(
            name="UnitConverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_from", models.CharField(max_length=20)),
                ("unit_to", models.CharField(max_length=20)),
                ("factor", models.DecimalField(decimal_places=5, max_digits=12)),
            ],
            options={
                "verbose_name": "Przelicznik jednostek",
                "verbose_name_plural": "Przeliczniki jednostek",
                "db_table": "tbl_converters",
            },
        ),
    ]
