# Generated by Django 6.0.4 on 2026-05-17 18:03

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = []
