# Generated by Django 6.0.4 on 2026-05-17 18:03


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = []
