# Generated by Django 6.0.4 on 2026-05-17 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('data_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('energy_source', models.CharField(max_length=100)),
                ('energy_type', models.CharField(max_length=100)),
                ('emission_tco2eq', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Zużycie energii',
                'verbose_name_plural': 'Zużycie energii',
                'db_table': 'tbl_e_cons',
            },
        ),
        migrations.CreateModel(
            name='EnergyProduced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('data_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('installation', models.CharField(blank=True, default='', max_length=200)),
                ('energy_type', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Wyprodukowana energia',
                'verbose_name_plural': 'Wyprodukowana energia',
                'db_table': 'tbl_e_prod',
            },
        ),
        migrations.CreateModel(
            name='EnergyPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('data_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('energy_type', models.CharField(max_length=100)),
                ('trader', models.CharField(blank=True, default='', max_length=200)),
                ('factor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('emission_tco2eq', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Zakupiona energia',
                'verbose_name_plural': 'Zakupiona energia',
                'db_table': 'tbl_e_purc',
            },
        ),
        migrations.CreateModel(
            name='EnergySold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('data_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('energy_type', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Sprzedana energia',
                'verbose_name_plural': 'Sprzedana energia',
                'db_table': 'tbl_e_sold',
            },
        ),
    ]
