# Generated by Django 6.0.4 on 2026-05-31 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_companies_nip"),
        ("emissions", "0002_energyconsumption_energyproduced_energypurchased_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyconsumption",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="energyproduced",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="energypurchased",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="energysold",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="fugitiveemission",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="mobilecombustion",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="processemission",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
        migrations.AlterField(
            model_name="stationarycombustion",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="companies.companies",
            ),
        ),
    ]
