# Generated by Django 6.0.4 on 2026-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0003_alter_energyconsumption_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyconsumption",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="energyproduced",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="energypurchased",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="energysold",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="fugitiveemission",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="mobilecombustion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="processemission",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="stationarycombustion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Do akceptacji"),
                    ("APPROVED", "Zatwierdzony"),
                    ("VERIFIED", "Zweryfikowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
