# Generated by Django 6.0.4 on 2026-06-08 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0005_delete_changelog_delete_reductiontarget_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fugitiveemission",
            name="notes",
        ),
    ]
