# Generated by Django 6.0.4 on 2026-06-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_alter_fuelspec_supplier"),
        ("companies", "0002_alter_companies_nip"),
        ("emissions", "0007_alter_emissionfactor_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionfactor",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emission_factors",
                to="companies.countries",
                verbose_name="Kraj",
            ),
        ),
        migrations.AlterField(
            model_name="mobilecombustion",
            name="fuel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mobile_combustion",
                to="calculator.fueltype",
                verbose_name="Paliwo",
            ),
        ),
        migrations.AlterField(
            model_name="stationarycombustion",
            name="fuel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stationary_combustions",
                to="calculator.fueltype",
                verbose_name="Paliwo",
            ),
        ),
    ]
