# Generated by Django 6.0.4 on 2026-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emissions", "0008_alter_emissionfactor_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyconsumption",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="energyproduced",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="energypurchased",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="energysold",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fugitiveemission",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecombustion",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processemission",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stationarycombustion",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Roboczy"),
                    ("PENDING", "Oczekuje na akceptację"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
