# Generated by Django 6.0.4 on 2026-07-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0009_energyconsumption_workflow_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energyconsumption",
            name="status",
        ),
        migrations.RemoveField(
            model_name="energyproduced",
            name="status",
        ),
        migrations.RemoveField(
            model_name="energypurchased",
            name="status",
        ),
        migrations.RemoveField(
            model_name="energysold",
            name="status",
        ),
        migrations.RemoveField(
            model_name="fugitiveemission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="mobilecombustion",
            name="status",
        ),
        migrations.RemoveField(
            model_name="processemission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="stationarycombustion",
            name="status",
        ),
    ]
