# Generated by Django 6.0.4 on 2026-08-09 08:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companiesgroup_options_alter_countries_options_and_more'),
        ('emissions', '0010_remove_energyconsumption_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='energysold',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Wskaźnik'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipients',
            field=models.CharField(max_length=1000, verbose_name='Odbiorcy'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='record_ids',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID rekordów'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='scope',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zakres'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sender',
            field=models.CharField(max_length=100, verbose_name='Nadawca'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Temat'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='table_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa tabeli'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='template_type',
            field=models.CharField(max_length=50, verbose_name='Typ szablonu'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='factor',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Wartość wskaźnika'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='factor_name',
            field=models.CharField(max_length=200, verbose_name='Nazwa wskaźnika'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='unit_factor',
            field=models.CharField(max_length=50, verbose_name='Jednostka wskaźnika'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='energy_source',
            field=models.CharField(max_length=100, verbose_name='Źródło energii'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='energy_type',
            field=models.CharField(max_length=100, verbose_name='Typ energii'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='energy_type',
            field=models.CharField(max_length=100, verbose_name='Typ energii'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Wskaźnik'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='installation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Instalacja'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='energyproduced',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='energy_type',
            field=models.CharField(max_length=100, verbose_name='Typ energii'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Wskaźnik'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='trader',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dostawca'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='energypurchased',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Odbiorca'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='energy_type',
            field=models.CharField(max_length=100, verbose_name='Typ energii'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='installation',
            field=models.CharField(max_length=200, verbose_name='Instalacja'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='product',
            field=models.CharField(max_length=200, verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='raport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Raport'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='fugitiveemission',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='raport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Raport'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='vehicle',
            field=models.CharField(max_length=200, verbose_name='Pojazd'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='mobilecombustion',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='process',
            field=models.CharField(max_length=200, verbose_name='Proces'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='product',
            field=models.CharField(max_length=200, verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='raport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Raport'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='processemission',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.companies', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='data_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jakość danych'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='installation',
            field=models.CharField(max_length=200, verbose_name='Instalacja'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='raport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Raport'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Źródło danych'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Roboczy'), ('PENDING', 'Oczekuje na akceptację'), ('APPROVED', 'Zaakceptowany'), ('REJECTED', 'Odrzucony')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status workflow'),
        ),
        migrations.AlterField(
            model_name='stationarycombustion',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
    ]
