# Generated by Django 6.0.4 on 2026-06-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChangeLog",
        ),
    ]
