# Generated by Django 6.0.4 on 2026-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_delete_changelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id_rejestr_zmian",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=100)),
                ("date_change", models.DateTimeField()),
                ("table_name", models.CharField(max_length=200)),
                ("record_id", models.CharField(max_length=50)),
                ("change_type", models.CharField(max_length=10)),
                ("previous_data", models.TextField(blank=True, null=True)),
                ("actual_data", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log zmian",
                "verbose_name_plural": "Logi zmian",
                "db_table": "tbl_change_log",
            },
        ),
    ]
