# Generated by Django 6.0.4 on 2026-07-01 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChangeLog",
        ),
    ]
