# Generated by Django 6.0.4 on 2026-07-02 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_delete_changelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(max_length=255)),
                ("url_path", models.CharField(max_length=255)),
                ("visit_count", models.PositiveIntegerField(default=1)),
                ("last_visited", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_page_views",
                "indexes": [
                    models.Index(
                        fields=["user", "-visit_count"],
                        name="user_page_v_user_id_f3e48b_idx",
                    )
                ],
                "unique_together": {("user", "view_name")},
            },
        ),
    ]
