# Generated by Django 6.0.4 on 2026-08-09 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usercarbonfootprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercarbonfootprint',
            options={'verbose_name': 'Ślad węglowy użytkownika', 'verbose_name_plural': 'Ślady węglowe użytkowników'},
        ),
        migrations.AlterModelOptions(
            name='userpageview',
            options={'verbose_name': 'Wyświetlenie strony użytkownika', 'verbose_name_plural': 'Wyświetlenia stron użytkowników'},
        ),
        migrations.AlterField(
            model_name='usercarbonfootprint',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja'),
        ),
        migrations.AlterField(
            model_name='usercarbonfootprint',
            name='total_emissions_kg',
            field=models.FloatField(default=0.0, verbose_name='Całkowita emisja (kg CO2eq)'),
        ),
        migrations.AlterField(
            model_name='usercarbonfootprint',
            name='total_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Całkowita liczba zapytań'),
        ),
        migrations.AlterField(
            model_name='usercarbonfootprint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_stats', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='userpageview',
            name='last_visited',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnio odwiedzone'),
        ),
        migrations.AlterField(
            model_name='userpageview',
            name='url_path',
            field=models.CharField(max_length=255, verbose_name='Ścieżka URL'),
        ),
        migrations.AlterField(
            model_name='userpageview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='userpageview',
            name='view_name',
            field=models.CharField(max_length=255, verbose_name='Nazwa widoku'),
        ),
        migrations.AlterField(
            model_name='userpageview',
            name='visit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Liczba odwiedzin'),
        ),
    ]
