# Generated by Django 6.0.4 on 2026-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=200)),
                ("operation", models.CharField(max_length=10)),
                ("record_id", models.CharField(db_index=True, max_length=50)),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Log zmian",
                "verbose_name_plural": "Logi zmian",
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="audit_log_table_n_38ccfb_idx",
                    )
                ],
            },
        ),
    ]
