# Generated by Django 6.0.4 on 2026-07-01 20:51

from django.db import migrations

SQL_CREATE_TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS trigger AS $$
DECLARE
    v_current_user_id text;
    v_audit_row audit_log%ROWTYPE;
BEGIN
    BEGIN
        v_current_user_id := current_setting('app.current_user_id', true);
    EXCEPTION WHEN OTHERS THEN
        v_current_user_id := NULL;
    END;
    v_audit_row.table_name := TG_TABLE_NAME;
    v_audit_row.operation := TG_OP;
    v_audit_row.created_at := CURRENT_TIMESTAMP;
    IF v_current_user_id IS NOT NULL AND v_current_user_id <> '' THEN
        v_audit_row.user_id := v_current_user_id::bigint;
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_audit_row.record_id := NEW.id::text;
        v_audit_row.new_data := row_to_json(NEW)::jsonb;
        INSERT INTO audit_log VALUES (v_audit_row.*);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        v_audit_row.record_id := NEW.id::text;
        v_audit_row.old_data := row_to_json(OLD)::jsonb;
        v_audit_row.new_data := row_to_json(NEW)::jsonb;
        IF v_audit_row.old_data <> v_audit_row.new_data THEN
            INSERT INTO audit_log VALUES (v_audit_row.*);
        END IF;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        v_audit_row.record_id := OLD.id::text;
        v_audit_row.old_data := row_to_json(OLD)::jsonb;
        INSERT INTO audit_log VALUES (v_audit_row.*);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""

SQL_DROP_TRIGGER_FUNC = "DROP FUNCTION IF EXISTS audit_trigger_func;"


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [migrations.RunSQL(SQL_CREATE_TRIGGER_FUNC, SQL_DROP_TRIGGER_FUNC)]
