# Generated by Django 6.0.4 on 2026-07-01 21:22

from django.db import migrations

SQL_FIX_TRIGGER_FUNC = """
                       CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS trigger AS $$
DECLARE
    v_current_user_id text;
    v_audit_row audit_log%ROWTYPE;
BEGIN
    BEGIN
        v_current_user_id := current_setting('app.current_user_id', true);
    EXCEPTION WHEN OTHERS THEN
        v_current_user_id := NULL;
    END;

    v_audit_row.table_name := TG_TABLE_NAME;
    v_audit_row.operation := TG_OP;
    v_audit_row.created_at := CURRENT_TIMESTAMP;

    IF v_current_user_id IS NOT NULL AND v_current_user_id <> '' THEN
        v_audit_row.user_id := v_current_user_id::bigint;
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_audit_row.record_id := NEW.id::text;
        v_audit_row.new_data := row_to_json(NEW)::jsonb;
        INSERT INTO audit_log (table_name, operation, record_id, old_data, new_data, user_id, created_at)
        VALUES (v_audit_row.table_name, v_audit_row.operation, v_audit_row.record_id, v_audit_row.old_data, v_audit_row.new_data, v_audit_row.user_id, v_audit_row.created_at);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        v_audit_row.record_id := NEW.id::text;
        v_audit_row.old_data := row_to_json(OLD)::jsonb;
        v_audit_row.new_data := row_to_json(NEW)::jsonb;

        IF v_audit_row.old_data <> v_audit_row.new_data THEN
            INSERT INTO audit_log (table_name, operation, record_id, old_data, new_data, user_id, created_at)
            VALUES (v_audit_row.table_name, v_audit_row.operation, v_audit_row.record_id, v_audit_row.old_data, v_audit_row.new_data, v_audit_row.user_id, v_audit_row.created_at);
        END IF;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        v_audit_row.record_id := OLD.id::text;
        v_audit_row.old_data := row_to_json(OLD)::jsonb;
        INSERT INTO audit_log (table_name, operation, record_id, old_data, new_data, user_id, created_at)
        VALUES (v_audit_row.table_name, v_audit_row.operation, v_audit_row.record_id, v_audit_row.old_data, v_audit_row.new_data, v_audit_row.user_id, v_audit_row.created_at);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auto_20260701_2051"),
    ]

    operations = [migrations.RunSQL(SQL_FIX_TRIGGER_FUNC)]
