# Generated by Django 6.0.4 on 2026-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReductionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("target_name", models.CharField(max_length=300)),
                ("base_year", models.PositiveIntegerField()),
                ("target_year", models.PositiveIntegerField()),
                ("reduction_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scope", models.CharField(default="1+2", max_length=10)),
            ],
            options={
                "verbose_name": "Cel redukcji",
                "verbose_name_plural": "Cele redukcji",
                "db_table": "tbl_reduction_targets",
            },
        ),
    ]
