# Generated by Django 6.0.4 on 2026-06-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_companies_nip"),
        ("what_if", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reductiontarget",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reduction_targets",
                to="companies.companies",
                verbose_name="Firma",
            ),
        ),
    ]
