# Generated by Django 6.0.4 on 2026-06-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("what_if", "0002_alter_reductiontarget_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reductiontarget",
            name="scope",
            field=models.CharField(
                choices=[
                    ("Scope 1", "Zakres 1 (Emisje bezpośrednie)"),
                    ("Scope 2", "Zakres 2 (Emisje pośrednie energetyczne)"),
                    ("1+2", "Zakres 1 + Zakres 2"),
                ],
                default="1+2",
                max_length=10,
                verbose_name="Zakres (Scope)",
            ),
        ),
    ]
