# Generated by Django 6.0.4 on 2026-07-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_options_companies_is_active'),
        ('what_if', '0003_alter_reductiontarget_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reductiontarget',
            options={'verbose_name': 'Przypisanie celu', 'verbose_name_plural': 'Przypisania celów'},
        ),
        migrations.CreateModel(
            name='ReductionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa celu')),
                ('base_year', models.PositiveIntegerField(verbose_name='Rok bazowy')),
                ('target_year', models.PositiveIntegerField(verbose_name='Rok docelowy')),
                ('reduction_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Docelowa redukcja (%)')),
                ('scope', models.CharField(choices=[('Scope 1', 'Zakres 1 (Emisje bezpośrednie)'), ('Scope 2', 'Zakres 2 (Emisje pośrednie energetyczne)'), ('1+2', 'Zakres 1 + Zakres 2')], default='1+2', max_length=10, verbose_name='Zakres (Scope)')),
                ('company', models.ForeignKey(blank=True, help_text='Jeśli wybierzesz spółkę, cel będzie widoczny tylko dla niej.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_goals', to='companies.companies', verbose_name='Dedykowana spółka (zostaw puste = cel globalny)')),
            ],
            options={
                'verbose_name': 'Cel redukcji (Globalny)',
                'verbose_name_plural': 'Cele redukcji (Globalne)',
                'db_table': 'tbl_reduction_goals',
            },
        ),
        migrations.AddField(
            model_name='reductiontarget',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_targets', to='what_if.reductiongoal', verbose_name='Przypisany cel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reductiontarget',
            unique_together={('company', 'goal')},
        ),
        migrations.RemoveField(
            model_name='reductiontarget',
            name='base_year',
        ),
        migrations.RemoveField(
            model_name='reductiontarget',
            name='reduction_pct',
        ),
        migrations.RemoveField(
            model_name='reductiontarget',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='reductiontarget',
            name='target_name',
        ),
        migrations.RemoveField(
            model_name='reductiontarget',
            name='target_year',
        ),
    ]
