# Generated by Django 6.0.4 on 2026-07-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_options_companies_is_active'),
        ('what_if', '0004_reductiongoal_alter_reductiontarget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reductiongoal',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Jeśli wybierzesz spółkę, cel będzie widoczny tylko dla niej.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_goals', to='companies.companies', verbose_name='Dedykowana spółka (zostaw puste = cel globalny)'),
        ),
        migrations.AlterUniqueTogether(
            name='reductiontarget',
            unique_together={('company', 'goal')},
        ),
    ]
