# Generated by Django 6.0.4 on 2026-08-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_if', '0004_alter_reductiontarget_options_reductiongoal_and_more'),
        ('what_if', '0005_reductiongoal_company_and_more'),
    ]

    operations = [
    ]
