# Generated by Django 6.0.4 on 2026-06-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelspec",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_specs",
                to="calculator.supplier",
            ),
        ),
    ]
