# Generated by Django 6.0.4 on 2026-08-09 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_fuelspec_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelspec',
            options={'verbose_name': 'Specyfikacja paliwa', 'verbose_name_plural': 'Specyfikacje paliw'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Typ paliwa', 'verbose_name_plural': 'Typy paliw'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Dostawca', 'verbose_name_plural': 'Dostawcy'},
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='calorific_mj_per_kg',
            field=models.FloatField(null=True, verbose_name='Wartość opałowa (MJ/kg)'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='calorific_mj_per_m3',
            field=models.FloatField(null=True, verbose_name='Wartość opałowa (MJ/m³)'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='density_kg_per_m3',
            field=models.FloatField(null=True, verbose_name='Gęstość (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='calculator.fueltype', verbose_name='Typ paliwa'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Domyślny'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_specs', to='calculator.supplier', verbose_name='Dostawca'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='fuelspec',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa typu paliwa'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył(-a)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa dostawcy'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizował(-a)'),
        ),
    ]
