# Generated by Django 6.0.4 on 2026-05-17 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompanypermission",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_permissions",
                to="companies.companies",
                verbose_name="Firma",
            ),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="companies",
            field=models.ManyToManyField(
                related_name="users",
                through="accounts.UserCompanyPermission",
                through_fields=("user", "company"),
                to="companies.companies",
                verbose_name="Firmy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercompanypermission",
            unique_together={("user", "company")},
        ),
    ]
