# Generated by Django 6.0.4 on 2026-07-03 11:10

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Zdjęcie profilowe'),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('secret', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Zaszyfrowany sekret TOTP')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktywne 2FA')),
                ('name', models.CharField(blank=True, default='Default', max_length=100, verbose_name='Nazwa urządzenia')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Potwierdzone')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnio użyte')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Urządzenie TOTP',
                'verbose_name_plural': 'Urządzenia TOTP',
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_device_name')],
            },
        ),
    ]
